### ISSUE TITLE
I can't install this application

### ISSUE THREAD

**Issue by DoobCaveman** [sparkchaser/swgoh-ui#1]
Hi,
I can't install this application, and I can't find why it does not work.
First, I tried to install it on Heroku with various .NET package builders (like this one "https://buildpack-registry.s3.amazonaws.com/buildpacks/lstoll/heroku-buildpack-monorepo.tgz"), but it failed to build each time.
Second, I tried to deploy the project on Visual Studio 2019 and Studio 2013, but each time I received the following error:
"this project is incompatible with the current edition".
So, what are the tool needed to deploy this?

Thanks a lot,
Caveman

**Comment by sparkchaser** [comment]
There are pre-built binaries available.  Click "releases" on the main page and look for the zip file in the "Assets" dropdown.  Just extract the zip file somewhere and run the program, no installation required.

You can also build it from source if you want.  I used Visual Studio 2019 (community edition) to make it, but I think it should work in 2017 as well.  I haven't ever encountered that particular Visual Studio error before so I'm afraid I don't have a specific answer for you.  I'll suggest that you double-check that your install of Visual Studio includes the tools for desktop development for .NET 4.7.  I'd really hope that VS would give you a more informative error message than that if that was the problem, but you never know.

**Comment by DoobCaveman** [comment]
Thanks a lot for your help! I tried to clone the git repo, and Visual Studio asked me to install "desktop development". After that, it worked like a charm!
I tried to run it outside, but I could not find an exe or dll. So I tried to build it with the "msbuild.exe", but it didn't work.
I don't know if there is something more simple, like .net core, which might work.

**Comment by sparkchaser** [comment]
If the build completes successfully, you should have a `/bin/Debug/net47/*.exe` file (or `Release` if you built a release build).  If that file or directory _isn't_ there, then you likely encountered a build problem.  You may have to right-click on the solution and click "Restore NuGet packages" if your VS isn't configured to do that automatically during the build process.

Within Visual Studio, you should also be able to use the "Debug" drop-down menu and select either "Start Debugging" or "Start Without Debugger" to run the program with or without the debugger, respectively.

**Comment by DoobCaveman** [comment]
Indeed, I found it in `/bin/Debug/net47/` like you said! Thanks a lot for your help! Now, I am trying the program! Should I close this thread, then?

**Comment by sparkchaser** [comment]
I'll close it out.  I'm glad to hear that it's working for you!
